import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { ToggleButton } from "../button/toggleButton";
import { Navigation } from "./navigation";

export const Header: NextPage = () => {
  const [open, setOpen] = useState(false);
  const toggleFunction = () => {
    setOpen((prevState) => !prevState);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="header">
        <h2>YoutubeAPI</h2>
        <ToggleButton
          open={open}
          controls="navigation"
          label="menu"
          onClick={toggleFunction}
        />
        <Navigation id="navigation" open={open} />
      </header>
    </div>
  );
};
